Assignment 3 - TouristiqueBangladesh/TouristiqueBangladesh/Models/TouristSpot.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace TouristiqueBangladesh.Models
{
    public class TouristSpot
    {
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string Address { get; set; }

        [Range(1, 5)]
        public int Rating { get; set; }

        [Display(Name = "Picture")]
        public string ImagePath { get; set; }

        [NotMapped]
        public HttpPostedFileBase ImageFile { get; set; }
    }

    public class TouristSpotDBContext : DbContext
    {
        public DbSet<TouristSpot> TouristSpots { get; set; }
    }
}

Assignment 3 - TouristiqueBangladesh/TouristiqueBangladesh/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TouristiqueBangladesh.Models;

namespace TouristiqueBangladesh.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Assignment 3 - TouristiqueBangladesh/TouristiqueBangladesh/Controllers/TouristSpotController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TouristiqueBangladesh.Models;
using System.IO;
using System.Net;
using System.Data.Entity;

namespace TouristiqueBangladesh.Controllers
{
    public class TouristSpotController : Controller
    {
        private TouristSpotDBContext db = new TouristSpotDBContext();

        // GET: TouristSpot
        public ActionResult Index(string searchText, string sortBy)
        {
            var touristSpots = db.TouristSpots.AsQueryable();
            if(!String.IsNullOrEmpty(searchText))
            {
                touristSpots = touristSpots.Where(s => s.Name.ToLower().Contains(searchText.ToLower()) || s.Address.ToLower().Contains(searchText.ToLower()));
            }
            switch(sortBy)
            {
                case "Rating":
                    touristSpots = touristSpots.OrderBy(x => x.Rating);
                    break;
                case "Rating desc":
                    touristSpots = touristSpots.OrderByDescending(x => x.Rating);
                    break;
                case "Name desc":
                    touristSpots = touristSpots.OrderByDescending(x => x.Name);
                    break;
                default:
                    touristSpots = touristSpots.OrderBy(x => x.Name);
                    break;
            }
            ViewBag.SortNameParameter = String.IsNullOrEmpty(sortBy) ? "Name desc" : "";
            ViewBag.SortRatingParameter = sortBy == "Rating" ? "Rating desc" : "Rating";
            return View(touristSpots.ToList());
        }

        // GET: TouristSpot/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TouristSpot spot = db.TouristSpots.Find(id);
            if (spot == null)
            {
                return HttpNotFound();
            }
            return View(spot);
        }

        // GET: TouristSpot/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TouristSpot/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TouristSpot spot)
        {
            string path = Server.MapPath("~/App_Data/Images");
            string imageName = Path.GetFileName(spot.ImageFile.FileName);
            string fullPath = Path.Combine(path, imageName);

            spot.ImagePath = fullPath;
            spot.ImageFile.SaveAs(fullPath);


            if (ModelState.IsValid)
            {
                db.TouristSpots.Add(spot);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(spot);
        }

        // GET: TouristSpot/Edit/1
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TouristSpot spot = db.TouristSpots.Find(id);
            if(spot == null)
            {
                return HttpNotFound();
            }
            return View(spot);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id, Name, Address, Rating, ImageFile")] TouristSpot spot)
        {

            if(ModelState.IsValid)
            {
                db.Entry(spot).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(spot);
        }

        // GET: TouristSpot/Delete/1
        public ActionResult Delete(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TouristSpot spot = db.TouristSpots.Find(id);
            if (spot == null)
            {
                return HttpNotFound();
            }
            return View(spot);
        }
    }
}

Assignment 3 - TouristiqueBangladesh/TouristiqueBangladesh/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Assignment 3 - TouristiqueBangladesh/TouristiqueBangladesh/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Assignment 3 - TouristiqueBangladesh/TouristiqueBangladesh/Views/Home/Index.cshtml
@model IEnumerable<TouristiqueBangladesh.Models.TouristSpot>
@{
    ViewBag.Title = "Home Page";
    int i = 0;
}

<h1 class="content-title">Tourist Places in Bangladesh</h1>
<div class="container-native">
    <div class="table-container">
        <i class="fas fa-search" style="color: #2c2f33;"></i>
        <input type="text" name="search" id="search" placeholder="Search Here..">
        @Html.ActionLink("Create New Place", "Create")
        <table class="content-table">
            <thead>
                <tr>
                    <th class="sortableColumn">
                        <span>@Html.DisplayNameFor(model => model.Name) </span>
                        <span class="sortIcon">
                            <i class="fas fa-sort-up" id="ascending-name"></i><i class="fas fa-sort-down" id="descending-name"></i>
                        </span>
                    </th>
                    <th style="text-align:center">@Html.DisplayNameFor(model => model.Address)</th>
                    <th class="sortableColumn">
                        <span>@Html.DisplayNameFor(model => model.Rating)</span>
                        <span class="sortIcon">
                            <i class="fas fa-sort-up" id="ascending-rating"></i><i class="fas fa-sort-down" id="descending-rating"></i>
                        </span>
                    </th>
                    <th style="text-align:center">@Html.DisplayNameFor(model => model.ImagePath)</th>
                    <th style="text-align:center" colspan="2">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr id="@i">
                        <td>@Html.DisplayFor(modelItem => item.Name)</td>
                        <td>@Html.DisplayFor(modelItem => item.Address) </td>
                        <td>@Html.DisplayFor(modelItem => item.Rating)/10</td>
                        <td>
                            <img src=@Html.DisplayFor(modelItem => item.ImagePath)>
                        </td>
                        <td><button class="btn updateBtn">Update</button></td>
                        <td><button class="btn deleteBtn">Delete</button></td>
                    </tr>
                }
            </tbody>
            <tfoot>

            </tfoot>
        </table>
    </div>
</div>

Assignment 3 - TouristiqueBangladesh/TouristiqueBangladesh/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Touristique Bangladesh</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("styles", required: false)
</head>
<body>
    @Html.Partial("_Navbar")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Touristique Bangladesh</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Assignment 3 - TouristiqueBangladesh/TouristiqueBangladesh/Views/Shared/_Navbar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Touristique Bangladesh", "Index", "TouristSpot", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "TouristSpot")</li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
            </ul>
        </div>
    </div>
</div>

Assignment 3 - TouristiqueBangladesh/TouristiqueBangladesh/Views/TouristSpot.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

Assignment 3 - TouristiqueBangladesh/TouristiqueBangladesh/Views/TouristSpot/Create.cshtml
@model TouristiqueBangladesh.Models.TouristSpot

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Create";
}

@section Styles {
    @Styles.Render("~/Content/myStyle.css")
}

@using (Html.BeginForm("Create", "TouristSpot", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h1 class="content-title">Add New Tourist Spot</h1>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="ImageFile" required />
            @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="Btn defaultBtn" />
        </div>
    </div>
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>
}

Assignment 3 - TouristiqueBangladesh/TouristiqueBangladesh/Views/TouristSpot/Delete.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Delete";
}

@model TouristiqueBangladesh.Models.TouristSpot

@section Styles {
    @Styles.Render("~/Content/myStyle.css")  
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Movie</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rating)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="Btn defaultBtn" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Assignment 3 - TouristiqueBangladesh/TouristiqueBangladesh/Views/TouristSpot/Details.cshtml
@model TouristiqueBangladesh.Models.TouristSpot
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = Model.Name + "-Details";
}

@section Styles {
    @Styles.Render("~/Content/myStyle.css")
}


<h1 class="content-title">Details</h1>

<div>
    <h4>Tourist Spot</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rating)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>
        <dd>
            <img src="@Html.DisplayFor(model => model.ImagePath)">
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Assignment 3 - TouristiqueBangladesh/TouristiqueBangladesh/Views/TouristSpot/Edit.cshtml
@model TouristiqueBangladesh.Models.TouristSpot
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = Model.Name + "-Edit";
}

@section Styles {
    @Styles.Render("~/Content/myStyle.css")
}


<h1 class="content-title">Edit Spot</h1>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="ImageFile"/>
            @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Submit" class="Btn defaultBtn" />
        </div>
    </div>
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>
}

Assignment 3 - TouristiqueBangladesh/TouristiqueBangladesh/Views/TouristSpot/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model IEnumerable<TouristiqueBangladesh.Models.TouristSpot>
@{
    ViewBag.Title = "Home Page";
    int i = 0;
}

@section Styles {
    @Styles.Render("~/Content/myStyle.css")
}

@section Scripts {
    @Scripts.Render("https://kit.fontawesome.com/3bc4247b4f.js")
    @Scripts.Render("~/Scripts/main.js")
}

<h1 class="content-title">Tourist Places in Bangladesh</h1>
<div class="container-native">
    <div class="table-container">
        @using (Html.BeginForm("Index", "TouristSpot", routeValues: new { sortBy = Request.QueryString["sortBy"] }, method: FormMethod.Get))
        {
            <i class="fas fa-search" style="color: #2c2f33;"></i>
            @Html.TextBox("searchText", "", new { placeholder = "Search here..." })
            <input type="submit" value="Filter" class="Btn defaultBtn" />
        }
        <br />
        @Html.ActionLink("Create New Place", "Create", null, new { @class = "Btn addNewPlaceBtn" })
        @*<input type="text" name="search" id="search" placeholder="Search Here..">*@
        <table class="content-table">
            <thead>
                <tr>
                    <th class="sortableColumn">
                        @Html.ActionLink("Name", "Index", new { sortBy = ViewBag.SortNameParameter, searchText = Request["searchText"] })
                    </th>
                    <th style="text-align:center">@Html.DisplayNameFor(model => model.Address)</th>
                    <th class="sortableColumn">
                        @Html.ActionLink("Rating", "Index", new { sortBy = ViewBag.SortRatingParameter, searchText = Request["searchText"] })
                    </th>
                    <th style="text-align:center">@Html.DisplayNameFor(model => model.ImagePath)</th>
                    <th style="text-align:center" colspan="2">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr id="@i">
                        <td>
                            @Html.ActionLink(item.Name, "Details", new { id = item.Id })
                        </td>
                        <td>@Html.DisplayFor(modelItem => item.Address) </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Rating)/5
                        </td>
                        <td>
                            <img src="@Html.DisplayFor(modelItem => item.ImagePath)">
                        </td>
                        <td>@Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "Btn updateBtn" })</td>
                        <td>@Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "Btn deleteBtn" })</td>
                    </tr>
                    i++;
                }
            </tbody>
            <tfoot>

            </tfoot>
        </table>
    </div>
</div>